{
    'name': 'SMS ATTENDANCE',
    'version': '1.0',
    'author': 'Inovtec Solutions',
    'category': 'SMS Attendance Management',
    'description': """This Module is used for attendance management for Compas Managment System.""",
    'website': 'http://www.inovtec.com.pk',
    'images': [''],
    'depends' : ['base','account','account_accountant','sms'],
    'data': [
             'sms_attendance_view.xml',
             'wizard/sms_wizard_punched_attendance_report_view.xml',
           #  'sms_attendance_report.xml',
             'sms_attendance_menu.xml',
            ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': [],
}
